# Generated by Django 4.2.3 on 2023-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='blogpic'),
        ),
    ]
