# Generated by Django 4.2.3 on 2023-09-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
    ]
