# Generated by Django 4.2.3 on 2023-09-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_content_remove_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=13)),
                ('proimage', models.ImageField(blank=True, null=True, upload_to='projectpic')),
            ],
        ),
    ]
