# Generated by Django 4.2.3 on 2023-09-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myprojects',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('mydesc', models.TimeField()),
                ('proimage', models.ImageField(blank=True, null=True, upload_to='projectpic')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
